### ISSUE TITLE
Clicking on a bomb does not stop the game

### ISSUE THREAD

**Issue by moredatapls** [ddneat/minesweeper#2]
Steps to reproduce:
- Start a new game
- Find a bomb
- Continue clicking

**Comment by ddneat** [comment]
@hbrgnr thanks for your feedback. Actually I already would have an updated versions, which includes that feature. However I did not manage to polish it yet. I will let you know as soon as I release this version.

May I recommend you to just reload the page in the meantime? :)

Cheers

**Comment by ddneat** [comment]
@hbrgnr I just released a new version.

Just make sure that you clear your browser cache. Enjoy!
